export { OrbitClient } from './client.js'
export type { OrbitClientOptions } from './config.js'
export { OrbitApiError } from './errors.js'
export type { OrbitTransport, TransportRequest } from './transport/index.js'
export { AutoPager } from './pagination.js'
export { SearchResource } from './search.js'
export type { SearchInput } from './search.js'

export { BaseResource } from './resources/base-resource.js'
export { ContactResource } from './resources/contacts.js'
export { CompanyResource } from './resources/companies.js'
export { DealResource } from './resources/deals.js'
export { PipelineResource } from './resources/pipelines.js'
export { StageResource } from './resources/stages.js'
export { UserResource } from './resources/users.js'

export type { ContactRecord, CreateContactInput, UpdateContactInput } from './resources/contacts.js'
export type { CompanyRecord, CreateCompanyInput, UpdateCompanyInput } from './resources/companies.js'
export type { DealRecord, CreateDealInput, UpdateDealInput } from './resources/deals.js'
export type { PipelineRecord, CreatePipelineInput, UpdatePipelineInput } from './resources/pipelines.js'
export type { StageRecord, CreateStageInput, UpdateStageInput } from './resources/stages.js'
export type { UserRecord, CreateUserInput, UpdateUserInput } from './resources/users.js'
