export { OrbitClient } from './client.js'
export type { OrbitClientOptions } from './config.js'
export { OrbitApiError } from './errors.js'
export type { OrbitTransport, TransportRequest } from './transport/index.js'
export { AutoPager } from './pagination.js'
export { SearchResource } from './search.js'
export type { SearchInput } from './search.js'

// Wave 1 resources
export { BaseResource } from './resources/base-resource.js'
export { ContactResource } from './resources/contacts.js'
export { CompanyResource } from './resources/companies.js'
export { DealResource } from './resources/deals.js'
export { PipelineResource } from './resources/pipelines.js'
export { StageResource } from './resources/stages.js'
export { UserResource } from './resources/users.js'

export type { ContactRecord, CreateContactInput, UpdateContactInput } from './resources/contacts.js'
export type { CompanyRecord, CreateCompanyInput, UpdateCompanyInput } from './resources/companies.js'
export type { DealRecord, CreateDealInput, UpdateDealInput } from './resources/deals.js'
export type { PipelineRecord, CreatePipelineInput, UpdatePipelineInput } from './resources/pipelines.js'
export type { StageRecord, CreateStageInput, UpdateStageInput } from './resources/stages.js'
export type { UserRecord, CreateUserInput, UpdateUserInput } from './resources/users.js'

// Wave 2 resources
export { ActivityResource } from './resources/activities.js'
export { TaskResource } from './resources/tasks.js'
export { NoteResource } from './resources/notes.js'
export { ProductResource } from './resources/products.js'
export { PaymentResource } from './resources/payments.js'
export { ContractResource } from './resources/contracts.js'
export { SequenceResource } from './resources/sequences.js'
export { SequenceStepResource } from './resources/sequence-steps.js'
export { SequenceEnrollmentResource } from './resources/sequence-enrollments.js'
export { SequenceEventResource } from './resources/sequence-events.js'
export { TagResource } from './resources/tags.js'
export { SchemaResource } from './resources/schema.js'
export { WebhookResource } from './resources/webhooks.js'
export { ImportResource } from './resources/imports.js'

export type { ActivityRecord, CreateActivityInput, UpdateActivityInput } from './resources/activities.js'
export type { TaskRecord, CreateTaskInput, UpdateTaskInput } from './resources/tasks.js'
export type { NoteRecord, CreateNoteInput, UpdateNoteInput } from './resources/notes.js'
export type { ProductRecord, CreateProductInput, UpdateProductInput } from './resources/products.js'
export type { PaymentRecord, CreatePaymentInput, UpdatePaymentInput } from './resources/payments.js'
export type { ContractRecord, CreateContractInput, UpdateContractInput } from './resources/contracts.js'
export type { SequenceRecord, CreateSequenceInput, UpdateSequenceInput } from './resources/sequences.js'
export type { SequenceStepRecord, CreateSequenceStepInput, UpdateSequenceStepInput } from './resources/sequence-steps.js'
export type { SequenceEnrollmentRecord, CreateSequenceEnrollmentInput, UpdateSequenceEnrollmentInput } from './resources/sequence-enrollments.js'
export type { SequenceEventRecord } from './resources/sequence-events.js'
export type { TagRecord, CreateTagInput, UpdateTagInput } from './resources/tags.js'
export type { WebhookRecord, CreateWebhookInput, UpdateWebhookInput } from './resources/webhooks.js'
export type { ImportRecord, CreateImportInput } from './resources/imports.js'
