export { BaseResource } from './base-resource.js'
export { ContactResource } from './contacts.js'
export { CompanyResource } from './companies.js'
export { DealResource } from './deals.js'
export { PipelineResource } from './pipelines.js'
export { StageResource } from './stages.js'
export { UserResource } from './users.js'

export type { ContactRecord, CreateContactInput, UpdateContactInput } from './contacts.js'
export type { CompanyRecord, CreateCompanyInput, UpdateCompanyInput } from './companies.js'
export type { DealRecord, CreateDealInput, UpdateDealInput } from './deals.js'
export type { PipelineRecord, CreatePipelineInput, UpdatePipelineInput } from './pipelines.js'
export type { StageRecord, CreateStageInput, UpdateStageInput } from './stages.js'
export type { UserRecord, CreateUserInput, UpdateUserInput } from './users.js'
